### ISSUE TITLE
Could not find a declaration file for module 'debug' on build with TS 4.5+

### ISSUE THREAD

**Issue by hugazo** [hannoeru/vite-plugin-pages#194]
Since i updated to TypeScript 4.5+ i'm having errors with `vue-tsc --noEmit && vite build` command.

If i add the `compilerOptions.skipLibCheck: true` to my `tsconfig.json` the error skips since there is no check on node_modules types.

**Proposed Solution**: just add the `@types/debug` to the devDependencies in the project dependencies.

node_modules/vite-plugin-pages/dist/index.d.ts:1:24 - error TS7016: Could not find a declaration file for module 'debug'. '/home/hugo/development/42academy-new/node_modules/debug/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`
